### ISSUE TITLE
Release package on PyPI automatically when a Git tag is pushed

### ISSUE THREAD

**Issue by bittner** [PyCQA/pylint-plugin-utils#18]
To remove the burden on the maintainer(s) I'd suggest to make it easier to release a new package version on PyPI. Pushing a Git tag to the repository may trigger an automatic release.

That can be achieved by adding a `deploy:` section to the Travis CI configuration, the same way the [Pylint project](https://github.com/PyCQA/pylint/blob/master/.travis.yml#L60-L68) has done it:

```yaml
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: <maintainer-pypi-username-here>
  password:
    secure: <maintainer-pypi-password-here>
  on:
    tags: true
```

This approach has several advantages:

- You don't need to install and configure software locally to trigger releases
- You don't accidentally [release from the wrong branch](https://github.com/PyCQA/pylint-plugin-utils/commit/37a2c5d6307160839be64ecb78747676e2610c74) (:hankey: happens!)
- Everyone who has permissions to push a tag on the repository directly can effortlessly trigger a release
- Releases, since they are tagged commits, automatically show up in the "releases" tab of the GitHub repo
